### ISSUE TITLE
Submenu items automatically refresh after any script execution.

### ISSUE THREAD

**Issue by aayushrg7** [harilvfs/carch#11]
### Description

When a script runs from the sub-menu and completes or exits, returning to the sub-menu by pressing Enter automatically refreshes the selection and moves to the top, instead of staying on the previously selected script.

### Environment

- **OS**: Arch Linux
- **Shell**: Bash
- **Script Version**: v3.0.3
- **Terminal Emulator**: Alacritty

### Script Behavior

After running a script from the sub-menu, the selection refreshes and defaults to the first item in the list, rather than preserving the position of the previously selected script.

### Expected Behavior

The selection in the sub-menu should stay on the previously selected script after it completes or exits, instead of automatically moving to the top. This would allow users to continue running scripts or navigating from where they left off without having to scroll back to the original position.

### Additional Context

This behavior disrupts workflows where multiple scripts need to be run consecutively, as users are forced to repeatedly scroll back to the previous script. Ideally, the sub-menu should maintain the script's selection position even after execution, providing a smoother experience.
@harilvfs

**Comment by harilvfs** [comment]
Fix this issue in PR #12
